require 'fileutils'

$version = "1.0.5"
$tools_path = "tools"

def GrabImageSize(location) #grabs Image size
	input = `magick identify "#{location}"`
	values = input.split(" ")
	raw_size = values[values.length-7] #avoid spaces inside return data like this "C:\Users\maddo\Desktop\test test.png PNG 1920x1125 1920x1125+0+0 8-bit sRGB 1.95MB 0.000u 0:00.000"
	size = raw_size.split("x")
	#size[0] is width
	#size[1] is height
	return size
end

#generates Keyart_Input Folder
FileUtils::mkdir_p "Keyart_Input"
#Print Information
print "-----------------------------\nMaddox's Batch Keyart Generator for WoTB V.#{$version}\nMade By Maddox, MadWoTBMods\n- You MUST install ImageMagick In Order to use this. link to download: https://www.imagemagick.org/script/download.php\n- This KeyArt Generator for WoTB only supports .png input.\n- The optimal Input size will be 2728 x 1536. Other Input size are all accepted but it will be forced resize to 2728 x 1536  while attemtping to retain the aspect ratio.\n- Any Modification or Redistribution of this Tool must first notify Me.\n- The scripts directly processes every single .png file in Keyart_Input folder.\n- Development in Progress\n-----------------------------\nThe Script Already Generated the Keyart_Input folder.\nPress Enter If you are ready with everything"
gets

#Starts doing it's stuff

def Generation(definition, png_name)
	FileUtils::cp "#{$tools_path}/tex.tex", "Keyart_Output/#{png_name}/Data/#{definition}/UI/KeyArt/Mad_Easy_Keyart.tex"
		output_size = GrabImageSize("Keyart_Output/#{png_name}/Data/#{definition}/UI/KeyArt/Mad_Easy_Keyart.webp")
		open("Keyart_Output/#{png_name}/Data/#{definition}/UI/KeyArt/keyart.txt", 'w') { |content|
			content << "1\nMad_Easy_Keyart.tex\n#{output_size[0]} #{output_size[1]}\n1\n0 0 #{output_size[0]} #{output_size[1]} 0 0 0 MadWoTBMods0"
		}
		pixels = Integer(output_size[0])*Integer(output_size[1])
		open("Keyart_Output/#{png_name}/Data/#{definition}/UI/KeyArt/Mad_Easy_Keyart_size.txt", 'w') { |content|
			content << "(I#{pixels}\nI#{output_size[0]}\nI#{output_size[1]}\ntp0\n."
		}
end 

png_array = Dir.glob('Keyart_Input/*.png') #grab png array for the current directory
png_array.each do |png|
	#create Gfx and Gfx2 folder First
		png_name = File.basename(png, ".png")
		FileUtils::mkdir_p ["Keyart_Output/#{png_name}/Data/Gfx2/UI/KeyArt", "Keyart_Output/#{png_name}/Data/Gfx/UI/KeyArt"]
	#create Gfx2 data first
		cmd_return = `magick convert "#{png}" -resize 2728x1536 -quality 99 "Keyart_Output/#{png_name}/Data/Gfx2/UI/KeyArt/Mad_Easy_Keyart.webp"`
		Generation("Gfx2", png_name)
	#create Gfx data
		cmd_return = `magick convert "#{png}" -resize 1364x768 -quality 99 "Keyart_Output/#{png_name}/Data/Gfx/UI/KeyArt/Mad_Easy_Keyart.webp"`
		Generation("Gfx", png_name)
	open("Keyart_Output/#{png_name}/README.txt", 'w') { |content|
			content << "This Is a README File Generated by WoTB Easy Keyart, Developed my MadWoTBMods, with the assist of some individuals.\nThis Keyart can be installed as a normal mod. Just copy and paste the whole 'Data' folder to the correct place and it should work.\nThe Script can be downloaded here: https://github.com/MadWoTBMods/WoTB_Easy_Keyart"
	}
	puts "Finished Generating Keyart for #{png_name}...."
end

puts "Press Enter to end the script...."
gets


